### ISSUE TITLE
Problems running limelight on MacOS

### ISSUE THREAD

**Issue by nattzy94** [yeastrc/limelight-core#17]
Hi Michael,

Thanks for your help previously in converting my pep.xml for use with limelight. I am now trying to get limelight running on my laptop and would like to check if I am doing the right thing. 

I followed the installation instructions for MacOS up until the command to start limelight using `sudo docker-compose up --detach`. At this point, docker runs into the following error: 

```
b833d23ffb39: Pull complete
Digest: sha256:42b1bf35419c97dd4624bca075ef56de9001fdb91a8b560d7d534c387c4438e9
Status: Downloaded newer image for mriffle/limelight-webapp:1
Pulling smtp (bytemark/smtp:)...
latest: Pulling from bytemark/smtp
be8881be8156: Pull complete
bc3a79cd813e: Pull complete
18d54f745478: Pull complete
Digest: sha256:9fd6ff05ac25141fe10ae4f9db0df361ad6139244ac280c398cc175bd2356a98
Status: Downloaded newer image for bytemark/smtp:latest
Creating limelight-spectr ... done
Creating limelight-smtp   ... done
Creating limelight-mysql  ...

ERROR: for limelight-mysql  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for db  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

I then append `COMPOSE_HTTP_TIMEOUT=1000` to the end of the  `.env` file, restarted docker and reran `sudo docker-compose up --detach`. However, the same error comes up: 

```
Docker Compose is now in the Docker CLI, try `docker compose up`

limelight-spectr is up-to-date
limelight-smtp is up-to-date
Starting limelight-mysql ...

ERROR: for limelight-mysql  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=1000)
ERROR: for db  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=1000)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 1000).
```
I will try again tomorrow when I have access to my school's network. Otherwise, is there another way around this?

**Comment by mriffle** [comment]
Nathaniel,

I think this may be caused by running up against hardware resource limits. What are the specs on your mac? Namely RAM. As a server application Limelight uses quite a bit of RAM since it's running a database, two web applications, and an import program!  The Mac I have access to is my 2015 MacBook Pro with 16 gigs of RAM and it starts up OK on that (but I'm not running anything else). 

One thing to try:

Instead of putting ```COMPOSE_HTTP_TIMEOUT=1000``` in the .env file, try typing this into the terminal before running docker-compose:

```
export DOCKER_CLIENT_TIMEOUT=120
export COMPOSE_HTTP_TIMEOUT=120
```

Mike

**Comment by nattzy94** [comment]
Hi Michael,

I have now managed to run limelight by using an AWS EC2 instance. After installing limelight, I attempted to upload my limelight.xml file. However, the program runs into an error when uploading the data. See screenshots below:

<img width="727" alt="Screen Shot 2021-08-13 at 2 53 30 PM" src="https://user-images.githubusercontent.com/48880365/129317046-de361ff6-9f37-4ddc-9d12-64edf581446c.png">

<img width="986" alt="Screen Shot 2021-08-13 at 2 32 04 PM" src="https://user-images.githubusercontent.com/48880365/129316392-13f02987-8e7c-418c-96b4-ffe6d471841e.png">

Is there an issue with my xml file? I can share the file with you if needed. 
I would also like to visualise my spectra but it seems like limelight only takes mzXML scan files. I tried uploading my mgf file but ran into an error also

**Comment by mriffle** [comment]
First, thank you for your patience to get this worked out! I think there may be two issues going on.

Issue 1: The bottom image shows an error parsing the XML file. Is it possible to share teab.limelight.xml with me? Alternatively, can you paste in line 68? It looks like the value may be missing for a type of score in that file, but can't be sure without seeing it.

Issue 2: The 500 error from the server when you're uploading your file in the top image. Can you double check the disk space situation on your ec2 instance? Our best guess w/o seeing server logs is that the instance is out of diskspace, so the upload can't complete, thus the error.

Mike

**Comment by nattzy94** [comment]
Thanks for the reply and great support. I will email you the XML file. For the second issue, I will re-try this using a EC2 instance with more memory. Otherwise, is there a specific log file that I could check to see if disk space is the issue? The XML file itself is ~ 80 MB.

**Comment by nattzy94** [comment]
Hi Michael,

Thanks again for your help. I have uploaded the teab.limelight.xml file to this dropbox link: https://www.dropbox.com/sh/ptde7l69rknd8z2/AADBvUmz6Jx3ivJtV8UZjJ15a?dl=0 <https://www.dropbox.com/sh/ptde7l69rknd8z2/AADBvUmz6Jx3ivJtV8UZjJ15a?dl=0>. 

I tried sending the compressed file by email but it is still too large.

**Comment by mriffle** [comment]
Thanks for the file--looks like I incorrectly assumed there'd be values for XCorrs on all the PSMs. I'm going to run Tide on my end and duplicate that situation and fix it and I'll get back to you soon!

**Comment by nattzy94** [comment]
Hi Michael, have you had a chance to revisit this issue? Looking forward to get limelight up and running.

**Comment by mriffle** [comment]
Hi @nattzy94, I was on vacation last week, will take a look today!

**Comment by mriffle** [comment]
@nattzy94 Can you let me know the command line statement you're using to run crux? Are you using --exact-p-value?

**Comment by nattzy94** [comment]
Thanks for getting back so quickly. Hope you had an good vacation!

Yes, I did set `--exact-p-value T`. The full command line is below:

`crux tide-search --num-threads 0 --precursor-window 50 --output-dir $outDir --compute-sp T --score-function both --pepxml-output T --exact-p-value T --parameter-file $parameters `

I've also attached the full parameter file `crux.params.txt` that contains tide and comet search parameters.

[crux.params.txt](https://github.com/yeastrc/limelight-core/files/7035940/crux.params.txt)

**Comment by mriffle** [comment]
@nattzy94 OK, new version (1.3.0) of the converter is up: https://github.com/yeastrc/limelight-import-crux-tide-percolator/releases

This will support running with exact-p-value set and scoring type set to ```both``` or ```residue evidence```.  I generated test result sets (running tide with all the permutations of settings), converted results, and did test uploads of all the resulting limelight XML files and everything checked out.

Did you figure out the other error (where lack of disk space was the hypothesis)?

By the way, I am going to probably put up a public installation of Limelight this week where anyone can register for an account and upload data, if you're interested in that.

Mike

**Comment by nattzy94** [comment]
Hi Michael,

Thanks very much for setting up the new converter. I ran the following commands on my `tide xml file`:

```
perl -p -i -e 's/num_tol_term=\"\"/num_tol_term=\"2\"/g' tide-search.target.pep.xml
perl -p -i -e 's/date=\".+?\" /date=\"2020-01-07T17:05:18\" /g' tide-search.target.pep.xml
perl -p -i -e 's/mass=\"nan\"/mass=\"0.0\"/g' tide-search.target.pep.xml
perl -0777 -p -i -e 's/<\/modification_info>\n<modification_info.+//g' tide-search.target.pep.xml
perl -p -i -e 's/mass=\"nan\"/mass=\"0.0\"/g' tide-search.target.pep.xml
```
I then converted the `tide xml` to `limelight xml` using the new converter (v. 1.3.0) and uploaded to the limelight installation (v. 1.7.0). However, I get the following error this time:

<img width="951" alt="Screen Shot 2021-08-29 at 11 55 34 AM" src="https://user-images.githubusercontent.com/48880365/131237910-82cb3af4-2208-4ab3-99a9-6b95c223a3ff.png">

Perhaps I should try with a different version of limelight? I also can share the log file from the converter and the new xml file if needed.

**Comment by mriffle** [comment]
@nattzy94, I got your email with the Limelight XML file and was able to import it into limelight.

I suspect what's happening here is a disk space issue on the ec2 instance. I think it's possible to run out of disk space on upload and then have that partial XML file processed by the importer which would produce this error. Did you look at the disk space situation on the ec2 instance? I can't remember what kind of disk space is allocated by default with those instances, but I think it's pretty skimpy.  You can see how much diskspace is available by typing ```df -h``` on the command line in your ec2 instance--I'd think you'd want to have at least 10 gigabytes available if you are uploading spectra with your limelight xml file (possibly more if you are uploading more than one experiment).

I am setting up a public instance of Limelight as we speak and it should be ready in a day or two. If that's something you'd be interested in using, it would potentially save time debugging the ec2 instance.

Mike

**Comment by nattzy94** [comment]
Thanks for the tip, turns out it was indeed a disk space issue. I doubled the initial storage from 8 Gb to 16 Gb and the xml file was successfully uploaded. Thanks for all your help and patience.

I will now try uploading with the scan file. Does limelight accept mgf scan files? Or does it strictly have to be mzXML?

> I am setting up a public instance of Limelight as we speak and it should be ready in a day or two. If that's something you'd be interested in using, it would potentially save time debugging the ec2 instance.

I think this would be really helpful, and might test it out. However, I am not too comfortable uploading my data to a public instance as yet.

**Comment by mriffle** [comment]
Great, glad that worked! Just FYI: the "public" instance still has private projects (only researchers on that project can see it or its data unless you explicitly make it public). Public just means anyone can create an account--not that everyone's data is public. Perhaps I should think of a better name.
